name: Validate

on:
  push:
  pull_request:

jobs:
  hacs:
    name: HACS Validator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: HACS Validation
        uses: hacs/action@main
        with:
          category: integration
